@startuml

    !includesub ../../CERIF-Core/diagrams/core.puml!common

    !includesub ../../CERIF-Core/diagrams/core.puml!Document
    !includesub ../../CERIF-Core/diagrams/core.puml!Textual_Document

    !includesub ./module.puml!Journal

@enduml