@startuml

    !include ../../CERIF-Core/diagrams/core.puml

    !startsub COAR_Accessibility_Specification
        class "COAR_Accessibility_Specification_v_1_0" #ddeedd

        class "Open_Access_COAR_Accessibility_Specification_v_1_0" #ddeedd

        class "Restricted_Access_COAR_Accessibility_Specification_v_1_0" #ddeedd

        class "Metadata_Only_Access_COAR_Accessibility_Specification_v_1_0" #ddeedd

        class "Embargoed_Access_COAR_Accessibility_Specification_v_1_0" #ddeedd {
            embargoEndDate : Date
        }
    !endsub

    !startsub Journal
        class "Journal" #ddeedd {
            DOI : DOI
            startDate : Date
            endDate : Date
        }

        "Publication_Series" <|-- "Journal"

    !endsub

    !startsub Books_Series
        class "Books_Series" #ddeedd {
        }

        "Publication_Series" <|-- "Books_Series"
    !endsub

    !startsub Book
        class "Book" #ddeedd {
            ISBN : ISBN
            eISBN : ISBN
        }

        "Textual_Document" <|-- "Book"

        class "Monograph" #ddeedd {
        }

        "Book" <|-- "Monograph"

        class "Book_of_Chapters" #ddeedd {
        }

        "Book" <|-- "Book_of_Chapters"

        class "Proceedings" #ddeedd {
        }

        "Book" <|-- "Proceedings"

        "Proceedings" *-- "0..1" "Event" : event >


    !endsub

    !startsub Article
            class "Article" #ddeedd {
                startPage : String
                endPage : String
                numberOfPages : Decimal
                articleNumber : String
            }

            "Textual_Document" <|-- "Article"

            class "Book_Chapter" #ddeedd {
            }

            "Article" <|-- "Book_Chapter"
            "Book_Chapter" *-- "1" "Book_of_Chapters"

            class "Conference_Article" #ddeedd {
            }

            "Article" <|-- "Conference_Article"
            "Conference_Article" *-- "0..1" "Proceedings"

             class "Journal_Article" #ddeedd {
                volume : String
                number : String
             }

             "Article" <|-- "Journal_Article"
        !endsub

    class "Editorship" #ddeedd {
        leadingEditorFlag : Boolean
    }
    class "Publishership" #ddeedd {
        leadingPublisherFlag : Boolean
    }

    !startsub CRediT
        class "CRediT_Contribution_Statement" #ddeedd {
        }
        enum "CRediT_Degree_of_Contribution" #ddeedd {
            Lead
            Supporting
            Equal
        }
        enum "CRediT_Role_Type" #ddeedd {
            Conceptualization
            Data curation
            Formal analysis
            Funding acquisition
            Investigation
            Methodology
            Project administration
            Resources
            Software
            Supervision
            Validation
            Visualization
            Writing – original draft
            Writing – review & editing
        }
    !endsub

    !startsub COAR_Accessibility_Specification
        "Textual_Document_Accessibility_Specification" <|-- "COAR_Accessibility_Specification_v_1_0"
    !endsub
    !startsub COAR_Accessibility_Specification
        "COAR_Accessibility_Specification_v_1_0" <|-- "Open_Access_COAR_Accessibility_Specification_v_1_0"
    !endsub
    !startsub COAR_Accessibility_Specification
        "COAR_Accessibility_Specification_v_1_0" <|-- "Restricted_Access_COAR_Accessibility_Specification_v_1_0"
    !endsub
    !startsub COAR_Accessibility_Specification
        "COAR_Accessibility_Specification_v_1_0" <|-- "Embargoed_Access_COAR_Accessibility_Specification_v_1_0"
    !endsub
    !startsub COAR_Accessibility_Specification
        "COAR_Accessibility_Specification_v_1_0" <|-- "Metadata_Only_Access_COAR_Accessibility_Specification_v_1_0"
    !endsub
    "Contribution" <|-- "Editorship"
    "Contribution" <|-- "Publishership"
    !startsub CRediT
        "Contribution_Statement" <|-- "CRediT_Contribution_Statement"
    !endsub
    !startsub Journal
        "Journal" o-- "0..* predecessors" "Journal"
    !endsub
    !startsub Journal
        "Journal" o--  "0..* publishers" "Agent"
    !endsub
    "Editorship" --> "editor" "Agent"
    note on link #ddeedd: editor == contributor
    "Publishership" --> "publisher" "Agent"
    note on link #ddeedd: publisher == contributor
    !startsub CRediT
        "CRediT_Contribution_Statement" ..> "roleType" "CRediT_Role_Type"
    !endsub
    !startsub CRediT
        "CRediT_Contribution_Statement" ..> "degreeOfContribution" "CRediT_Degree_of_Contribution"
    !endsub
    note right of CRediT_Role_Type #ddeedd: The CRediT is currently not expressed as Linked Open Data. \nWe hope it will be in the future. We estimate it will be more \nstraightforward for it to be exposed as a list of terms (perhaps \na SKOS concept scheme), rather than a class hierarchy. \nThis justifies our choice to model it as an enumeration rather \nthan a class hierarchy in our model.
@enduml