@startuml

!includesub core.puml!common

package "CERIF core" #EFEFEF{
    !include ./core.puml
}
    !startsub Coar
    class "COAR Accessibility Specification v1"

    class "Open Access COAR v1 Accessibility Specification"

    class "Restricted Access COAR v1 Accessibility Specification"

    class "Metadata Only Access COAR v1 Accessibility Specification"

    class "Emargoed Access COAR v1 Accessibility Specification"{
        embargoEndDate : Date
    }
    !endsub

    !startsub Journal
    class "Journal"{
        title : Multilingual_String
        acronym : Multilingual_String
        ISSN : ISSN_Type
        eISSN : ISSN_Type
        startDate : Date
        endDate : Date
        DOI : DOI_Type
    }
    class "Journal Article"{
        startPage : String
        endPage : String
        volume : String
        issue : String
    }
    !endsub

    class "Monograph"{
        ISBN : ISBN_Type
        eISBN : ISBN_Type
    }
    class "Editorship"{
        leadingEditorFlag : Boolean
    }
    class "Publishership"{
        leadingPublisherFlag : Boolean
    }
    !startsub CRediT
    class "CRediT Contribution Statement"{
    }
    enum "CRediT Degree of Contribution"{
        Lead
        Equal
        Supporting
    }
    enum "CRediT Role Type"{
        Conceptualization
        Data curation
        Formal analysis
        Funding acquisition
        Investigation
        Methodology
        Project administration
        Resources
        Software
        Supervision
        Validation
        Visualization
        Writing – original draft
        Writing – review & editing
    }
    !endsub

    !startsub Coar
    "Textual Document Accessibility Specification" <|-- "COAR Accessibility Specification v1"
    !endsub
    !startsub Coar
    "COAR Accessibility Specification v1" <|-- "Open Access COAR v1 Accessibility Specification"
    !endsub
    !startsub Coar
    "COAR Accessibility Specification v1" <|-- "Restricted Access COAR v1 Accessibility Specification"
    !endsub
    !startsub Coar
    "COAR Accessibility Specification v1" <|-- "Emargoed Access COAR v1 Accessibility Specification"
    !endsub
    !startsub Coar
    "COAR Accessibility Specification v1" <|-- "Metadata Only Access COAR v1 Accessibility Specification"
    !endsub
    !startsub Journal
    "Textual Document" <|-- "Journal Article"
    !endsub
    "Textual Document" <|-- "Monograph"
    "Contributorship" <|-- "Editorship"
    "Contributorship" <|-- "Publishership"
    !startsub CRediT
    "Contribution Statement" <|-- "CRediT Contribution Statement"
    !endsub
    !startsub Journal
    "Journal" o-- "predecessor" "Journal"
    !endsub
    "Journal" o--  "publishers" "Agent"
    !startsub Journal
    "Journal Article" o-- "source" "Journal"
    !endsub
    "Editorship" --> "editor" "Agent"
    note on link #red: editor == contributor
    "Publishership" --> "publisher" "Agent"
    note on link #red: publisher == contributor
    !startsub CRediT
    "CRediT Contribution Statement" ..> "roleType" "CRediT Role Type"
    "CRediT Contribution Statement" ..> "degreeOfContribution" "CRediT Degree of Contribution"
    !endsub

    note right of "CRediT Role Type": The CRediT is currently not expressed as Linked Open Data. \nWe hope it will be in the future. We estimate it will be more \nstraightforward for it to be exposed as a list of terms (perhaps \na SKOS concept scheme), rather than a class hierarchy. \nThis justifies our choice to model it as an enumeration rather \nthan a class hierarchy in our model.
@enduml