@startuml

    !includesub ../../CERIF-Core/diagrams/core.puml!common
    !includesub ../../CERIF-Core/diagrams/core.puml!Contribution_to_Document
    !includesub ../../CERIF-Core/diagrams/core.puml!Document
    !includesub ../../CERIF-Core/diagrams/core.puml!Publication_Channel
    !includesub ../../CERIF-Core/diagrams/core.puml!Form

    !includesub ./module.puml!Publication_Series
    !includesub ./module.puml!Journal
    !includesub ./module.puml!Scholarly_Publication
    !includesub ./module.puml!Article
    !includesub ./module.puml!Books_Series
    !includesub ./module.puml!Book


@enduml