name: generate plantuml
on: push
jobs:
  generate_plantuml:
    runs-on: ubuntu-latest
    name: plantuml
    steps:
      - name: Install Dependencies
        run: |
          sudo apt-get install graphviz
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Clone CERIF-Core
        run: git clone https://github.com/EuroCRIS/CERIF-Core.git ../CERIF-Core
      - name: Process Diagrams
        run: ../CERIF-Core/tools/generate-diagrams.sh
      - name: Commit Diagrams
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m ":rocket: adding generated diagrams" || exit 0
      - name: Push Diagrams
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
